### ISSUE TITLE
Basic touch

### ISSUE THREAD

**Issue by spirit89** [Bodmer/Touch_FT5x06#1]
Hello Basic touch will not compile 

Arduino: 1.8.13 (Windows 10), Board: "ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), DIO, 40MHz, 115200, None"

In file included from C:\Users\Dave\Documents\Arduino\Basic_touch\Basic_touch.ino:6:0:

C:\Users\Dave\Documents\Arduino\libraries\Touch_FT5x06/Touch_FT5x06.h: In function 'void loop()':

C:\Users\Dave\Documents\Arduino\libraries\Touch_FT5x06/Touch_FT5x06.h:147:20: error: 'int16_t Touch_FT5x06::pointX [5]' is private

   int16_t  pointX[5];  // x coordinates of touches

                    ^
Basic_touch:25:50: error: within this context

       Serial.print(": x = "); Serial.print(touch.pointX[0]);

                                                  ^

In file included from C:\Users\Dave\Documents\Arduino\Basic_touch\Basic_touch.ino:6:0:

C:\Users\Dave\Documents\Arduino\libraries\Touch_FT5x06/Touch_FT5x06.h:148:20: error: 'int16_t Touch_FT5x06::pointY [5]' is private

   int16_t  pointY[5];  // y coordinates of touches

                    ^

Basic_touch:26:52: error: within this context

       Serial.print(", y = "); Serial.println(touch.pointY[0]);
                                                    ^
exit status 1

Thanks Dave

**Comment by Bodmer** [comment]
Thanks for reporting this. I have corrected this now.
