### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by spirit89** [Bodmer/Touch_FT5x06#2]
Arduino: 1.8.15 (Windows 10), Board: "ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), DIO, 40MHz, 921600, None"

C:\Users\Dave\Documents\Arduino\Basic_touch\Basic_touch.ino: In function 'void loop()':

Basic_touch:25:61: error: invalid types '<unresolved overloaded function type>[int]' for array subscript

       Serial.print(": x = "); Serial.print(touch.getPointX[i]);

                                                             ^

Basic_touch:26:63: error: invalid types '<unresolved overloaded function type>[int]' for array subscript

       Serial.print(", y = "); Serial.println(touch.getPointY[i]);

                                                               ^
exit status 1

invalid types '<unresolved overloaded function type>[int]' for array subscript

Thanks Dave

**Comment by Bodmer** [comment]
Thanks, sketch needs a change so i is a uint8_t type:

```
   //    vvvvvvv
    for (uint8_t i = 1; i <= touches; i++) {
      Serial.print("Point "); Serial.print(i);
      Serial.print(": x = "); Serial.print(touch.getPointX(i));
      Serial.print(", y = "); Serial.println(touch.getPointY(i));
    }
```

Thanks for pointing this out.
